#pragma once
#define _CRT_SECURE_NO_WARNINGS
#include <iostream>
#include <opencv2/opencv.hpp>
#include <opencv2/dnn/dnn.hpp>
#include <iostream>
#include <fstream>
#include <vector>
#include <filesystem>
#include <string>
#include <direct.h>
#include <sys/stat.h>
#include <cstdio>
#include <cstring>
#include <errno.h>
#include <io.h>
#include <sstream>
#include <iomanip>